on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deployment CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH private key
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 400 key.pem
        env:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH and Pull Latest Changes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: key.pem
          port: 22
          script: |
            cd ${{ secrets.PATH_TO_FOLDER }}
            git pull origin master
            npm run build
            ./vendor/bin/sail build
            ./vendor/bin/sail down
            ./vendor/bin/sail up -d
